### ISSUE TITLE
Misuses of cryptographic APIs

### ISSUE THREAD

**Issue by mhp0rtal** [StreakYC/mache#22]
Hi
The following lines have cryptographic API misuses. <br> File name => src/main/java/com/streak/logging/utils/AnalysisUtility.java: Line number => 189: API name => MessageDigest:Unexpected call to method <java.security.MessageDigest: byte[] digest()> on object of type java.security.MessageDigest. Expect a call to one of the following methods <java.security.MessageDigest: void update(byte[])>,<java.security.MessageDigest: void update(byte[],int,int)>,<java.security.MessageDigest: byte[] digest(byte[])>,<java.security.MessageDigest: void update(java.nio.ByteBuffer)>,<java.security.MessageDigest: void update(byte)><BR> File name => src/main/java/com/streak/logging/utils/AnalysisUtility.java: Line number => 196: API name => MessageDigest:<BR>

**Comment by frew** [comment]
Hi @mhp0rtal 

My guess is that whatever you're running is worried that the previous loop might never execute, resulting in an empty digest? I don't believe that's the case and we're not relying on the cryptographic properties of MD5 here, but let me know if I'm missing something.

-Fred
